services:
  transmission:
    image: unixlinuxgeek/transmission
    network_mode: host
    restart: unless-stopped
    volumes:
      - <YOUR-PATH>/transmission/downloads:/transmission/downloads

  minidlna:
    image: unixlinuxgeek/minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      - <YOUR-PATH>/transmission/downloads:/transmission/downloads
      - <YOUR-PATH>/docker/minidlna/minidlna.conf:/etc/minidlna.conf

